Append

In [15]:
import numpy as np

In [16]:
# 1d Array
arr = np.arange(1,5)
arr 

array([1, 2, 3, 4])

In [17]:
# add a new element
new = np.append(arr,[6,7,8])
new 

array([1, 2, 3, 4, 6, 7, 8])

In [18]:
# 2d array
arr2D = np.random.randint(1,50,(4,5))
arr2D 

array([[14, 24, 29, 32, 18],
       [ 8, 42, 36, 22,  3],
       [13,  8, 22,  8, 19],
       [21, 26, 16, 27, 13]])

In [19]:
# insert at row 
new = np.append(arr2D,[[12,36,56,89,52]], axis=0)
new 

array([[14, 24, 29, 32, 18],
       [ 8, 42, 36, 22,  3],
       [13,  8, 22,  8, 19],
       [21, 26, 16, 27, 13],
       [12, 36, 56, 89, 52]])

In [20]:
# insert at column
new = np.append(arr2D, [[100],[200],[300],[400]], axis=1)
new 

array([[ 14,  24,  29,  32,  18, 100],
       [  8,  42,  36,  22,   3, 200],
       [ 13,   8,  22,   8,  19, 300],
       [ 21,  26,  16,  27,  13, 400]])

Insert at specific position

In [22]:
arr = np.arange(1,5,1)
arr 

array([1, 2, 3, 4])

In [23]:
new = np.insert(arr,2,[10,20])
new 

array([ 1,  2, 10, 20,  3,  4])

In [24]:
# insert at 2d array
a = np.random.randint(1,50,(4,3))
a 

array([[38, 35, 17],
       [24,  6, 35],
       [37,  9, 33],
       [ 8,  4, 49]])

In [31]:
# Insert at row 
new = np.insert(a,[1],20, axis=0)
new 

array([[38, 35, 17],
       [20, 20, 20],
       [24,  6, 35],
       [37,  9, 33],
       [ 8,  4, 49]])

In [34]:
# insert at column 
new = np.insert(a,1,[[100],[200],[300],[400]],axis=1)  
new 

array([[ 38, 100, 200, 300, 400,  35,  17],
       [ 24, 100, 200, 300, 400,   6,  35],
       [ 37, 100, 200, 300, 400,   9,  33],
       [  8, 100, 200, 300, 400,   4,  49]])

In [35]:
# Delete 
new = np.delete(a,1,axis=0)
new 

array([[38, 35, 17],
       [37,  9, 33],
       [ 8,  4, 49]])