In [1]:
import numpy as np

In [20]:
# 1D Array to 2D

arr = np.arange(1,25,1).reshape((4,6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [21]:
# Convert Multi-D array to 1D
arr1D = arr.flatten()
arr1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [28]:
# Transpose Matrix
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])