In [2]:
import numpy as np

In [2]:
# Create a 1D Array mannually 
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# dtype
arr = np.array([1,2,3,4.5,12.3], dtype=int)
arr

array([ 1,  2,  3,  4, 12])

In [4]:
# Create array from lists
li = [12,56,78,45,9,6]
arr = np.array(li)
arr

array([12, 56, 78, 45,  9,  6])

In [ ]:
arr.shape

(6,)

In [6]:
# Create a 2D array from 2D list
li = [[1,2],[3,4],[5,6]]
arr = np.array(li)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# Create 2D array mannually
arr2D = np.array([(1,2,3),(4,5,6)])
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2D.shape

(2, 3)

In [10]:
# Create 3D array from list 
li = [[[1,2],[3,4]],[[5,6],[7,8]]]
arr3D = np.array(li)
arr3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
arr2D.shape

(2, 3)

In [25]:
li = [1,2,3,"BCA"]
arr = np.array(li)
print(arr)
arr.dtype

['1' '2' '3' 'BCA']


dtype('<U11')

In [26]:
# Create array with values 0
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
ones = np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# create an array with a specific value
constant = np.full((2,2),5)
constant

array([[5, 5],
       [5, 5]])

In [35]:
# identity matrix
idm = np.eye(4)
idm

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
# Range array  (start,end, skip value or jump value)
arr = np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [48]:
# Linspace [ evenly space array (starting index, ending index, total values )]
evenlyspacearray = np.linspace(0,1,3)
evenlyspacearray

array([0. , 0.5, 1. ])

In [5]:
randomarray = np.random.random(2)
randomarray

array([0.23649789, 0.93969265])

In [6]:
randomint = np.random.randint(1,5,(2,2))
randomint

array([[1, 1],
       [3, 1]])