Numpy Array Indexing

In [1]:
import numpy as np

In [2]:
# 1D array
arr = np.arange(1,11,1)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[4]
arr[9]
arr[0]

1

In [10]:
arr = np.random.randint(1,20,(3,3))
arr 

array([[ 1, 18, 15],
       [11,  6, 10],
       [ 5,  4, 12]])

In [13]:
arr[0,2]

15

Numpy Array Slicing 

In [ ]:
arr = np.arange(6)
arr 

array([0, 1, 2, 3, 4, 5])

In [18]:
# Slice a specific range " : "
arr[2:5]

array([2, 3, 4])

In [19]:
arr[ : ]

array([0, 1, 2, 3, 4, 5])

In [21]:
arr[2: ]

array([2, 3, 4, 5])

In [22]:
arr[ : 2]

array([0, 1])

In [27]:
# Reverse a array
arr[ :: -1]

array([5, 4, 3, 2, 1, 0])

In [28]:
arr

array([0, 1, 2, 3, 4, 5])

In [30]:
arr[ :: 2]

array([0, 2, 4])

In [31]:
arr = np.random.randint(1,30,(5,5))
arr 

array([[23, 29, 29, 11,  6],
       [20, 16, 27, 17,  8],
       [ 9, 17, 28, 22, 20],
       [ 6, 27,  2,  8,  9],
       [21,  5,  7,  1, 14]])

In [32]:
# row s:e , c s:e
arr[ : 2, : 2]

array([[23, 29],
       [20, 16]])

In [33]:
arr[2: ,2: ]

array([[28, 22, 20],
       [ 2,  8,  9],
       [ 7,  1, 14]])

In [34]:
arr[ : , : ]

array([[23, 29, 29, 11,  6],
       [20, 16, 27, 17,  8],
       [ 9, 17, 28, 22, 20],
       [ 6, 27,  2,  8,  9],
       [21,  5,  7,  1, 14]])

In [36]:
arr[2:4, : 3]

array([[ 9, 17, 28],
       [ 6, 27,  2]])

In [ ]:
# Skipping rows  
arr[::2, :]

array([[23, 29, 29, 11,  6],
       [ 9, 17, 28, 22, 20],
       [21,  5,  7,  1, 14]])