In [2]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1," ",arr2)

[1 2 3 4]   [5 6 7 8]


In [5]:
# Addition
arr1 + arr2

array([ 6,  8, 10, 12])

In [6]:
# Subtraction
arr1 - arr2

array([-4, -4, -4, -4])

In [7]:
# Multiply
arr1 * arr2

array([ 5, 12, 21, 32])

In [9]:
# division
arr1 / arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [10]:
# remender
arr1 % arr2

array([1, 2, 3, 4])