In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# normal split
a1,a2 = np.split(arr,2)
print(a1,a2)

[1 2 3 4 5] [ 6  7  8  9 10]


In [6]:
# horizontal split
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
x,y =  np.hsplit(arr,2)
print(x,y) 

[[1 2]
 [5 6]] [[3 4]
 [7 8]]


In [8]:
# vertical slpit
a,b = np.vsplit(arr,2)
print(a,b)

[[1 2 3 4]] [[5 6 7 8]]
