In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3])
b = np.array([5,6,7])

# stack
st = np.stack((a,b))
print(st)

[[1 2 3]
 [5 6 7]]


In [6]:
# hsatck
st = np.hstack((a,b))
st

array([1, 2, 3, 5, 6, 7])

In [7]:
# vstack
st = np.vstack((a,b))
st

array([[1, 2, 3],
       [5, 6, 7]])

In [8]:
arr = np.array([1,2,5,3,1,56,8,6,1,5,4,6,1])
result = np.unique(arr)
result

array([ 1,  2,  3,  4,  5,  6,  8, 56])

In [9]:
np.sort(arr)

array([ 1,  1,  1,  1,  2,  3,  4,  5,  5,  6,  6,  8, 56])